### ISSUE TITLE
Data flows: Open Collective API, Community API and multiple databases

### ISSUE THREAD

**Issue by mhulet** [opencollective/community#1]
@danielsum @xdamman, acknowledging that:

* we better use Open Collective API for collectives, authentication, payments, etc.
* we will add features that will not fit into the Open Collective API
* some collectives will want to host this additional set of data

I was thinking about an architecture like this:

![Screenshot 2020-03-05 at 11 04 34](https://user-images.githubusercontent.com/293355/75971094-8d4c8700-5ed1-11ea-9711-55d240a985dd.png)

By default, Community-specific data will be hosted in the OCC database. But collectives might decide to take care of their own dataset, and host it on their own server/anywhere they want.

Technically, this means that the main set of data will come from the Open Collective database, but some extra features will get the data on the shared OCC database OR on a self-hosted database.

I don't know how this will be technically possible, but it seems to me that this is database multitenancy, something I've managed in the past on Rails apps with the [Apartment gem](https://github.com/influitive/apartment).

It seems to me that this kind of data architecture would be acceptable for most collectives who want to self-host, allowing us to keep the Community app itself shared across collectives, making it also way more easy to maintain.

What do you think? Do you have other suggestions?

**Comment by danielsum** [comment]
@mhulet => yes it's totally what I have in mind and what I put on my OC ecosystem diagram here : 

![Open Collective vision](https://user-images.githubusercontent.com/1868593/75972999-c0dce080-5ed4-11ea-9874-7ea6006ddfd4.png)

For me the OC Database, we could have some Read Replicas (multi-tenant) that could be mutualized for all the communities (maybe with a kind of membership fees) and doesn't affect the OC.com.

Every communities could create an OC app using their own Api Server / front-end and propose their app in an OC market.

The process of creating an app, should be eased by creating a "Feature request process", better onboarding for developers through doc/sdk and bounties.

This will really ease the adoption because what people will need to host their app is just an html server and a membership but they can after add extra features without depending on OC server/tech stack itself.

**Comment by mhulet** [comment]
Great, @danielsum ! That's already going further, with this awesome idea of a plugins store. I'd love to have this available, but how could we turn this into reality step by step? I have the feeling that your diagram is a long-term vision (that I absolutely share).

My main concern here is to know exactly what must be done to have our first version online (SaaS only). Seems like:

1. We need a fork of `opencollective-frontend`, connected to the `opencollective-api`
2. We need to start a new `community-api` (OCC API)

That's it? 🤔

And then, we should demonstrate that it is possible to have a self-hosted database for a collective (not just for a single plugin). This would meet data ownership needs for some collectives.

**Comment by danielsum** [comment]
@mhulet , yes of course it's the long term vision, for me first step = 

1. consolidate the front-app and adapt it to a test community hosting the community version
2. consolidate react components already available (maybe using typescript for all the OC components because it's hard to get in board for the moment at my view...) => maybe we can hide some components into a "Core" components app => the starter template could be clean at first side (I will need to check with our JS expert for that)

After that if everything is up and running, I thing that we could implement some features...

But for the moment I wouldn't go further than these two steps for me
